version: "3.9"

services:
  livro:
    build:
      context: livro-ms/.
    depends_on:
      - livro-db
    network_mode: bridge
  autor:
    build:
      context: autor-ms/.
    depends_on:
      - autor-db
    network_mode: bridge

  livro-db:
    image: postgres:latest
    ports:
      - "5432:5432"
  autor-db:
    image: postgres:latest
    ports:
      - "5432:5433"