version: "3.9"

services:
  front:
    container_name: front-ms
    build:
      context: front-ms/.

  livro:
    container_name: livro-ms
    build:
      context: livro-ms/.
    depends_on:
      - livro-db
  autor:
    container_name: autor-ms
    build:
      context: autor-ms/.
    depends_on:
      - autor-db
  livro-db:
    container_name: livro-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: livrodb
      POSTGRES_USER: livro
      POSTGRES_PASSWORD: livro
    healthcheck:
      test: pg_isready -U livro -d livrodb
      interval: 10s
      timeout: 3s
      retries: 3

  autor-db:
    container_name: autor-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: autordb
      POSTGRES_USER: autor
      POSTGRES_PASSWORD: autor
    healthcheck:
      test: pg_isready -U autor -d autordb
      interval: 10s
      timeout: 3s
      retries: 3

#  kafka:
#    container_name: kafka-ms
#    image: apache/kafka:latest
#    ports:
#      - "9002:9002"
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#      KAFKA_NUM_PARTITIONS: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - autor
      - livro

