spring.application.name=autor-ms
server.servlet.context-path=/api/autor

spring.datasource.url=jdbc:postgresql://autor-db:5432/autordb
spring.datasource.username=autor
spring.datasource.password=autor

spring.flyway.enabled=false