server {
    listen 80;

    location / {
        proxy_pass http://front:8080;
    }

    location /api/autor {
        proxy_pass http://autor:8080;
    }

    location /api/livro {
        proxy_pass http://livro:8080;
    }
}