spring.application.name=front-ms
server.servlet.session.tracking-modes=cookie

services.livro.url=${LIVRO_SERVICE_URL:http://localhost/api/livro}
services.autor.url=${AUTOR_SERVICE_URL:http://localhost/api/autor}
