spring.application.name=livro-ms
server.servlet.context-path=/api/livro

spring.datasource.url=jdbc:postgresql://livro-db:5432/livrodb
spring.datasource.username=livro
spring.datasource.password=livro

spring.flyway.enabled=false

